#from Week4 import birthday_paradox
#from Week4 import list_search
#from Week4 import basic_sort
#from Week4 import matrices
#from Week4 import scatterplot
#from Week5 import list_operations
#from Week5 import list_sort
#from Week5 import matrix_mult
#from Week5 import recursion   
#from Week5 import argument_types
#from Week6 import lists    
#from Week8 import recursive_sort
#from Week8 import binary_search
#from Week8 import binary_search_recursion
#from Week9 import file_handling
#from Week9 import search_in_file
#from Week9 import ceaser_cipher
#from Week9 import panda
#from Week10 import classes
#from Week10 import inheritance
#from Week10 import matplot
#from Week10 import twoplots
#from Week10 import grad10
#from Week11 import exceptions
#from Week11 import iterator
#from Week11 import generator
#from Week11 import grad11
#from practice import mat_mul
#from practice import mat_sum
#from practice import file_to_list
#from practice import longest_streak
from practice import digit_count

